# KNN : K Nearest Neighbor

K-Nearest Neighbors (KNN) is one of the simplest algorithms used in Machine Learning for regression and classification problem. KNN algorithms use data and classify new data points based on similarity measures (e.g. distance function). Classification is done by a majority vote to its neighbors

###  K :Number of selected nearest neighbours
![image.png](https://miro.medium.com/max/753/0*jqxx3-dJqFjXD6FA)

## Euclidean Distance and Manhattan Distance
![image.png](https://prismoskills.appspot.com/lessons/2D_and_3D_Puzzles/imgs/Manhattan_and_Euclidean.png)

### Eculidean vs Manhattan
![image.png](https://cstopics.github.io/cstopics/assets/img/AI/introAI/heuristic_ex.jpg)

# Code Implimentation

In [87]:
import pandas as pd
import numpy as np

In [88]:
columns=['sepal-length', 'sepal-width', 'petal-length', 'petal-width','type']
data = pd.read_csv('iris.csv', names = columns)

In [89]:
data.head()

sepal-length  sepal-width  petal-length  petal-width         type
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [90]:
x = data.iloc[:,0:4]

In [91]:
y = data.iloc[:,4:5]

In [92]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [93]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3)

In [94]:
#To Training the model and Nearest nighbors K=5
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(x_train, y_train)

C:\Users\deepc\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [95]:
#To make predictions on our test data
y_pred=classifier.predict(x_test)

In [96]:
print('Confusion Matrix')
print(confusion_matrix(y_test,y_pred))


Confusion Matrix
[[15  0  0]
 [ 0 18  1]
 [ 0  0 11]]


In [97]:
print('Accuracy Metrics')
print(classification_report(y_test,y_pred)) 

Accuracy Metrics
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        15
Iris-versicolor       1.00      0.95      0.97        19
 Iris-virginica       0.92      1.00      0.96        11

       accuracy                           0.98        45
      macro avg       0.97      0.98      0.98        45
   weighted avg       0.98      0.98      0.98        45



In [98]:
acc = accuracy_score(y_test, y_pred)
print(acc)

0.9777777777777777
